package ipsec

import (
	"net/netip"
	"strings"
	"testing"
	"time"
)

// clientConn is a valid client-side connection used as the base for
// table-driven variations.
func clientConn() Connection {
	return Connection{
		Name:       "egressa-gw-hk",
		Epoch:      7,
		LocalAddr:  netip.MustParseAddr("192.0.2.1"),
		RemoteAddr: netip.MustParseAddr("192.0.2.2"),
		LocalID:    "client-1",
		RemoteID:   "gw-hk",
		Auth:       AuthPSK,
		PSK:        "s3cr3t-psk-value-0123",
		LocalTS:    []netip.Prefix{netip.MustParsePrefix("10.201.0.2/32")},
		RemoteTS:   []netip.Prefix{netip.MustParsePrefix("0.0.0.0/0")},
		IfID:       42,
		DPDDelay:   10 * time.Second,
	}
}

func gatewayConn() Connection {
	return Connection{
		Name:      "egressa-client-1",
		Epoch:     7,
		LocalAddr: netip.MustParseAddr("192.0.2.2"),
		LocalID:   "gw-hk",
		RemoteID:  "client-1",
		Auth:      AuthPSK,
		PSK:       "s3cr3t-psk-value-0123",
		LocalTS:   []netip.Prefix{netip.MustParsePrefix("0.0.0.0/0")},
		RemoteTS:  []netip.Prefix{netip.MustParsePrefix("10.201.0.2/32")},
		IfID:      43,
	}
}

func TestConnection_Validate_Valid(t *testing.T) {
	for name, c := range map[string]Connection{"client": clientConn(), "gateway": gatewayConn()} {
		if err := c.Validate(); err != nil {
			t.Errorf("%s: Validate() = %v, want nil", name, err)
		}
	}
	pk := clientConn()
	pk.Auth, pk.PSK, pk.LocalPubkey, pk.RemotePubkey = AuthPubkey, "", "client-1.pub", "gw-hk.pub"
	if err := pk.Validate(); err != nil {
		t.Errorf("pubkey: Validate() = %v, want nil", err)
	}
}

func TestConnection_Validate_Rejects(t *testing.T) {
	cases := map[string]func(*Connection){
		"empty name":         func(c *Connection) { c.Name = "" },
		"name with space":    func(c *Connection) { c.Name = "gw hk" },
		"name with brace":    func(c *Connection) { c.Name = "gw{hk" },
		"start needs remote": func(c *Connection) { c.RemoteAddr = netip.Addr{}; c.Start = StartStart },
		"mixed families":     func(c *Connection) { c.RemoteAddr = netip.MustParseAddr("2001:db8::2") },
		"zoned address": func(c *Connection) {
			c.LocalAddr = netip.MustParseAddr("fe80::1%eth0")
			c.RemoteAddr = netip.MustParseAddr("fe80::2")
		},
		"empty local id":         func(c *Connection) { c.LocalID = "" },
		"id with space":          func(c *Connection) { c.RemoteID = "gw hk" },
		"id injecting a section": func(c *Connection) { c.RemoteID = "gw}\n  evil {" },
		"short psk":              func(c *Connection) { c.PSK = "short" },
		"psk with quote":         func(c *Connection) { c.PSK = `aaaaaaaaaaaaaaaa"bbb` },
		"psk with backslash":     func(c *Connection) { c.PSK = `aaaaaaaaaaaaaaaa\bbb` },
		"psk with space":         func(c *Connection) { c.PSK = "aaaaaaaa aaaaaaaaaa" },
		"psk with newline":       func(c *Connection) { c.PSK = "aaaaaaaaaaaaaaaa\nsecret" },
		"unknown auth":           func(c *Connection) { c.Auth = "eap" },
		"pubkey path traversal":  func(c *Connection) { c.Auth = AuthPubkey; c.LocalPubkey = "../x.pub"; c.RemotePubkey = "gw.pub" },
		"no local ts":            func(c *Connection) { c.LocalTS = nil },
		"no remote ts":           func(c *Connection) { c.RemoteTS = nil },
		"invalid ts":             func(c *Connection) { c.RemoteTS = []netip.Prefix{{}} },
		"zero if_id":             func(c *Connection) { c.IfID = 0 },
		"bad proposal":           func(c *Connection) { c.ESPProposals = []string{"aes256gcm16 x25519"} },
		"negative dpd":           func(c *Connection) { c.DPDDelay = -time.Second },
		"unknown start":          func(c *Connection) { c.Start = "trap-ish" },
	}
	for name, mutate := range cases {
		c := clientConn()
		mutate(&c)
		if err := c.Validate(); err == nil {
			t.Errorf("%s: Validate() = nil, want an error", name)
		}
	}
}

func TestRender_ClientConnection_Golden(t *testing.T) {
	got, err := Render([]Connection{clientConn()})
	if err != nil {
		t.Fatalf("Render: %v", err)
	}
	want := `# Generated by egressa (internal/ipsec). Do not edit by hand.
connections {
  egressa-gw-hk {
    version = 2
    local_addrs = 192.0.2.1
    remote_addrs = 192.0.2.2
    proposals = aes256gcm16-prfsha256-x25519
    dpd_delay = 10s
    local {
      auth = psk
      id = client-1
    }
    remote {
      auth = psk
      id = gw-hk
    }
    children {
      egressa-gw-hk-e7 {
        local_ts = 10.201.0.2/32
        remote_ts = 0.0.0.0/0
        esp_proposals = aes256gcm16-x25519
        mode = tunnel
        if_id_in = 42
        if_id_out = 42
        start_action = none
        dpd_action = clear
      }
    }
  }
}
secrets {
  ike-egressa-gw-hk {
    id-1 = client-1
    id-2 = gw-hk
    secret = 0x7333637233742d70736b2d76616c75652d30313233
  }
}
`
	if got != want {
		t.Fatalf("Render mismatch.\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

func TestRender_GatewayAcceptsAnyRemote_NoDPD(t *testing.T) {
	got, err := Render([]Connection{gatewayConn()})
	if err != nil {
		t.Fatalf("Render: %v", err)
	}
	for _, want := range []string{"remote_addrs = %any", "remote_ts = 10.201.0.2/32", "if_id_in = 43", "start_action = none"} {
		if !strings.Contains(got, want) {
			t.Errorf("rendered gateway config lacks %q:\n%s", want, got)
		}
	}
	for _, unwanted := range []string{"dpd_delay", "dpd_action"} {
		if strings.Contains(got, unwanted) {
			t.Errorf("rendered gateway config has %q although DPDDelay is 0", unwanted)
		}
	}
}

func TestConnection_RemoteIDAny(t *testing.T) {
	c := gatewayConn()
	c.RemoteID = AnyID
	if err := c.Validate(); err != nil {
		t.Fatalf("Validate with RemoteID %%any: %v", err)
	}
	got, err := Render([]Connection{c})
	if err != nil {
		t.Fatalf("Render: %v", err)
	}
	if !strings.Contains(got, "id = %any") {
		t.Errorf("rendered config lacks the %%any remote id:\n%s", got)
	}
	c.LocalID = AnyID
	if err := c.Validate(); err == nil {
		t.Error("Validate accepted %any as the local identity")
	}
}

func TestRender_PubkeyHasNoSecretsSection(t *testing.T) {
	c := clientConn()
	c.Auth, c.PSK, c.LocalPubkey, c.RemotePubkey = AuthPubkey, "", "client-1.pub", "gw-hk.pub"
	got, err := Render([]Connection{c})
	if err != nil {
		t.Fatalf("Render: %v", err)
	}
	if strings.Contains(got, "secrets") || strings.Contains(got, "secret =") {
		t.Errorf("pubkey config should carry no PSK secrets section:\n%s", got)
	}
	for _, want := range []string{"auth = pubkey", "pubkeys = client-1.pub", "pubkeys = gw-hk.pub"} {
		if !strings.Contains(got, want) {
			t.Errorf("rendered pubkey config lacks %q", want)
		}
	}
}

func TestRender_CustomProposalsAndStartAndIPv6(t *testing.T) {
	c := clientConn()
	c.LocalAddr = netip.MustParseAddr("2001:db8::1")
	c.RemoteAddr = netip.MustParseAddr("2001:db8::2")
	c.LocalTS = []netip.Prefix{netip.MustParsePrefix("fd00::2/128")}
	c.RemoteTS = []netip.Prefix{netip.MustParsePrefix("::/0"), netip.MustParsePrefix("10.0.0.0/8")}
	c.IKEProposals = []string{"aes128gcm16-prfsha256-ecp256", "aes256gcm16-prfsha384-x25519"}
	c.ESPProposals = []string{"aes128gcm16"}
	c.Start = StartStart
	c.DPDDelay = 1500 * time.Millisecond
	got, err := Render([]Connection{c})
	if err != nil {
		t.Fatalf("Render: %v", err)
	}
	for _, want := range []string{
		"local_addrs = 2001:db8::1",
		"proposals = aes128gcm16-prfsha256-ecp256,aes256gcm16-prfsha384-x25519",
		"esp_proposals = aes128gcm16",
		"remote_ts = ::/0,10.0.0.0/8",
		"start_action = start",
		"dpd_delay = 2s", // 1.5s rounded UP: DPD must never probe sooner than asked
	} {
		if !strings.Contains(got, want) {
			t.Errorf("rendered config lacks %q:\n%s", want, got)
		}
	}
}

func TestRender_MasksTrafficSelectors(t *testing.T) {
	c := clientConn()
	c.RemoteTS = []netip.Prefix{netip.MustParsePrefix("10.1.2.3/8")}
	got, err := Render([]Connection{c})
	if err != nil {
		t.Fatalf("Render: %v", err)
	}
	if !strings.Contains(got, "remote_ts = 10.0.0.0/8") {
		t.Errorf("traffic selector not masked:\n%s", got)
	}
}

func TestRender_DeterministicOrder(t *testing.T) {
	a, b := clientConn(), clientConn()
	b.Name, b.IfID, b.RemoteID = "egressa-gw-jp", 44, "gw-jp"
	one, err := Render([]Connection{a, b})
	if err != nil {
		t.Fatalf("Render: %v", err)
	}
	two, err := Render([]Connection{b, a})
	if err != nil {
		t.Fatalf("Render: %v", err)
	}
	if one != two {
		t.Fatal("Render output depends on input order")
	}
	if strings.Index(one, "egressa-gw-hk {") > strings.Index(one, "egressa-gw-jp {") {
		t.Fatal("connections not sorted by name")
	}
}

func TestRender_RejectsDuplicatesAndInvalid(t *testing.T) {
	a := clientConn()
	b := clientConn()
	b.IfID = 99
	if _, err := Render([]Connection{a, b}); err == nil {
		t.Error("duplicate connection names: expected an error")
	}
	c := clientConn()
	c.Name = "egressa-gw-jp"
	if _, err := Render([]Connection{a, c}); err == nil {
		t.Error("duplicate if_id: expected an error")
	}
	bad := clientConn()
	bad.IfID = 0
	if _, err := Render([]Connection{bad}); err == nil {
		t.Error("invalid connection: expected an error")
	}
}

func TestRender_Empty(t *testing.T) {
	got, err := Render(nil)
	if err != nil {
		t.Fatalf("Render(nil): %v", err)
	}
	if !strings.Contains(got, "connections {\n}\n") || strings.Contains(got, "secrets") {
		t.Fatalf("Render(nil) = %q, want an empty connections section and no secrets", got)
	}
}

func TestChildName_RoundTrip(t *testing.T) {
	for _, tc := range []struct {
		conn  string
		epoch uint64
	}{
		{"egressa-gw-hk", 0},
		{"egressa-gw-hk", 7},
		{"a-e", 12},                      // connection name itself ending in "-e"
		{"x-e5", 18446744073709551615},   // max uint64, and a name containing "-e<digits>"
		{"egressa_gw-jp", 1234567890123}, // underscore
		{"a", 1},
	} {
		child := ChildName(tc.conn, tc.epoch)
		conn, epoch, ok := ParseChildName(child)
		if !ok || conn != tc.conn || epoch != tc.epoch {
			t.Errorf("ParseChildName(ChildName(%q, %d) = %q) = (%q, %d, %v)", tc.conn, tc.epoch, child, conn, epoch, ok)
		}
	}
}

func TestParseChildName_RejectsForeignNames(t *testing.T) {
	for _, name := range []string{"", "net-net", "egressa-gw-hk", "-e5", "gw-e", "gw-ex", "gw-e+5", "gw-e-5", "gw-e05", "gw-e99999999999999999999"} {
		if _, _, ok := ParseChildName(name); ok {
			t.Errorf("ParseChildName(%q) ok=true, want false", name)
		}
	}
}

func TestRender_SecretAlwaysHex(t *testing.T) {
	// strongSwan would read a verbatim secret starting with "0x" as hex
	// and "0s" as base64; rendering hex always removes that ambiguity.
	c := clientConn()
	c.PSK = "0xdeadbeefdeadbeef00"
	got, err := Render([]Connection{c})
	if err != nil {
		t.Fatalf("Render: %v", err)
	}
	if !strings.Contains(got, "secret = 0x3078646561646265656664656164626565663030\n") {
		t.Fatalf("PSK not rendered as the hex of its literal bytes:\n%s", got)
	}
	if strings.Contains(got, c.PSK) {
		t.Fatal("PSK appears verbatim in the rendered config")
	}
}
